image: node:18
variables:
  AWS_ACCOUNT: "${{ values.awsAccount }}"
  AWS_DEFAULT_REGION: "${{ values.awsRegion }}"
  ROLE_ARN: "${{values.environmentRole}}"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"
  
stages:
  - build
  
include:
  - project: 'alithya-csna/cloud/aws/harmonix/reference'
    ref: main 
    file:
      - 'common/cicd/.gitlab-ci-aws-provider-ecs-ec2.yml'
